// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class MRole
{
    public int Roleid { get; set; }

    public string RoleName { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? Createdby { get; set; }

    public int? Updatedby { get; set; }

    public virtual MUser CreatedbyNavigation { get; set; }

    public virtual ICollection<MUser> MUsers { get; set; } = new List<MUser>();

    public virtual MUser UpdatedbyNavigation { get; set; }
}