// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class MTask
{
    public int Taskid { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int StatusId { get; set; }

    public int PriorityId { get; set; }

    public int AssignedTo { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? DueDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UPdatedbY { get; set; }

    public virtual MUser AssignedToNavigation { get; set; }

    public virtual TaskPriority Priority { get; set; }

    public virtual TaskStatus Status { get; set; }
}