// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class MUser
{
    public int Userid { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public int RoleId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? Createdby { get; set; }

    public int? Updatedby { get; set; }

    public virtual MUser CreatedbyNavigation { get; set; }

    public virtual ICollection<MUser> InverseCreatedbyNavigation { get; set; } = new List<MUser>();

    public virtual ICollection<MUser> InverseUpdatedbyNavigation { get; set; } = new List<MUser>();

    public virtual ICollection<MRole> MRoleCreatedbyNavigations { get; set; } = new List<MRole>();

    public virtual ICollection<MRole> MRoleUpdatedbyNavigations { get; set; } = new List<MRole>();

    public virtual ICollection<MTask> MTaskAssignedToNavigations { get; set; } = new List<MTask>();

    public virtual ICollection<MTask> MTaskCreatedByNavigations { get; set; } = new List<MTask>();

    public virtual ICollection<MTask> MTaskUPdatedbYNavigations { get; set; } = new List<MTask>();

    public virtual MRole Role { get; set; }

    public virtual MUser UpdatedbyNavigation { get; set; }
}