// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Role
{
    public int RoleId { get; set; }

    public string RoleName { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? Createdby { get; set; }

    public int? Updatedby { get; set; }

    public virtual User CreatedbyNavigation { get; set; }

    public virtual User UpdatedbyNavigation { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}