// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class TaskStatus
{
    public int TaskStatusId { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}