// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class TaskPriority
{
    public int TaskPriorityId { get; set; }

    public string PriorityName { get; set; }

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}