// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Task
{
    public int TaskId { get; set; }

    public string TaskName { get; set; }

    public string Description { get; set; }

    public int TaskStatusId { get; set; }

    public int? PriorityId { get; set; }

    public int AssignedTo { get; set; }

    public int CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? DueDate { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual User AssignedToNavigation { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual TaskPriority Priority { get; set; }

    public virtual TaskStatus TaskStatus { get; set; }

    public virtual User UpdatedByNavigation { get; set; }
}