// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class TaskPriority
{
    public int Taskpriorityid { get; set; }

    public string PriorityName { get; set; }

    public virtual ICollection<MTask> MTasks { get; set; } = new List<MTask>();
}