// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class User
{
    public int UserId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public int RoleId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? Createdby { get; set; }

    public int? Updatedby { get; set; }

    public virtual User CreatedbyNavigation { get; set; }

    public virtual ICollection<User> InverseCreatedbyNavigation { get; set; } = new List<User>();

    public virtual ICollection<User> InverseUpdatedbyNavigation { get; set; } = new List<User>();

    public virtual Role Role { get; set; }

    public virtual ICollection<Role> RoleCreatedbyNavigations { get; set; } = new List<Role>();

    public virtual ICollection<Role> RoleUpdatedbyNavigations { get; set; } = new List<Role>();

    public virtual ICollection<Task> TaskAssignedToNavigations { get; set; } = new List<Task>();

    public virtual ICollection<Task> TaskCreatedByNavigations { get; set; } = new List<Task>();

    public virtual ICollection<Task> TaskUpdatedByNavigations { get; set; } = new List<Task>();

    public virtual User UpdatedbyNavigation { get; set; }
}